/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_2 (
    input clk,
    input rst,
    input [63:0] red,
    input [63:0] blue,
    input [63:0] green,
    input [63:0] yellow,
    output reg [7:0] c_red,
    output reg [7:0] c_blue,
    output reg [7:0] c_green,
    output reg [7:0] row
  );
  
  
  
  localparam FLIP = 5'h10;
  
  wire [3-1:0] M_counter_r_value;
  counter_20 counter_r (
    .clk(clk),
    .rst(rst),
    .value(M_counter_r_value)
  );
  
  reg [2:0] whichrow;
  
  integer i;
  
  always @* begin
    c_red = 8'hff;
    c_blue = 8'hff;
    c_green = 8'hff;
    row = 8'h00;
    whichrow = M_counter_r_value;
    row[(whichrow)*1+0-:1] = 1'h1;
    for (i = 1'h0; i <= 3'h7; i = i + 1) begin
      c_red[(i)*1+0-:1] = ~red[(whichrow)*8+(i)*1+0-:1];
      c_blue[(i)*1+0-:1] = ~blue[(whichrow)*8+(i)*1+0-:1];
      c_green[(i)*1+0-:1] = ~green[(whichrow)*8+(i)*1+0-:1];
      if (yellow[(whichrow)*8+(i)*1+0-:1]) begin
        c_green[(i)*1+0-:1] = ~yellow[(whichrow)*8+(i)*1+0-:1];
        c_red[(i)*1+0-:1] = ~yellow[(whichrow)*8+(i)*1+0-:1];
      end
    end
  end
endmodule
