/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module timer_16 (
    input clk,
    input rst,
    output reg [7:0] out,
    input tozero
  );
  
  
  
  localparam TOP = 23'h4c4b3f;
  
  localparam SIZE = 5'h17;
  
  reg [22:0] M_counter_d, M_counter_q = 1'h0;
  
  localparam TOP2 = 8'hc7;
  
  localparam SIZE2 = 4'h8;
  
  reg [7:0] M_totalTime_d, M_totalTime_q = 1'h0;
  
  always @* begin
    M_counter_d = M_counter_q;
    M_totalTime_d = M_totalTime_q;
    
    out = M_totalTime_q;
    M_counter_d = M_counter_q + 1'h1;
    if (tozero) begin
      M_counter_d = 1'h0;
      M_totalTime_d = 1'h0;
    end else begin
      if (M_counter_q == 1'h0) begin
        M_totalTime_d = M_totalTime_q + 1'h1;
      end
      if (M_counter_q == 23'h4c4b3f) begin
        M_counter_d = 1'h0;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_totalTime_q <= 1'h0;
    end else begin
      M_totalTime_q <= M_totalTime_d;
    end
  end
  
endmodule
