/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module number_15 (
    output reg [63:0] number_map,
    input [2:0] output_number
  );
  
  
  
  always @* begin
    number_map = 64'h3844444444443800;
    
    case (output_number)
      1'h0: begin
        number_map = 64'h3844444444443800;
      end
      1'h1: begin
        number_map = 64'h3810101010181000;
      end
      2'h2: begin
        number_map = 64'h7c043c4040443800;
      end
      2'h3: begin
        number_map = 64'h3844403840443800;
      end
      3'h4: begin
        number_map = 64'h20207c2428302000;
      end
      3'h5: begin
        number_map = 64'h384440403c047c00;
      end
      3'h6: begin
        number_map = 64'h3844443c04443800;
      end
    endcase
  end
endmodule
